name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/TUB-CNPE-TB/user
    runs-on: ubuntu-latest
    env:
      GROUP: europe-west3-docker.pkg.dev/cnpe-blue/sockshop
      COMMIT: ${{ github.sha }}
      REPO: user
      REPO_DB: user-db
      GO_VERSION: 1.17
      GOPATH: /home/runner/work/user/user/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/TUB-CNPE-TB/user

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      #
      #
      # Build docker image for service
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}

      #
      #
      # Build docker image for database
      - name: Build database image
        uses: docker/build-push-action@v2
        with:
          push: false
          dockerfile: go/src/github.com/TUB-CNPE-TB/user/docker/user-db/Dockerfile
          path: go/src/github.com/TUB-CNPE-TB/user
          tags: ${{ env.GROUP }}/${{ env.REPO_DB }}:${{ github.sha }}

      #
      #
      # Login to GAR
      - name: Login to GAR
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      #
      #
      # Push to GAR
      - name: Push to GAR
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        run: docker push ${{ env.GROUP }}/${{ env.REPO }} --all-tags
      #
      # Push to GAR
      - name: Push DB to GAR
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        run: docker push ${{ env.GROUP }}/${{ env.REPO_DB }} --all-tags